### PR TITLE
Add search to documentation

### PR DESCRIPTION
**Pull request by julienbourdeau**
This is my contribution to add search capability to the composer.org website. I believe you have great content but it's not always easy to find what we're looking for.

I used [DocSearch](https://community.algolia.com/docsearch/) from Algolia, it powers the search of a lot of documentation, like Symfony, Laravel, Vue.js, Yarn or React for instance.

This PR aims to open a conversation. I tried to integrate it as well as possible. I'd be happy to edit my contribution according to your needs.

### Demo

composer-demo-docsearch

### CODE REVIEW

**Comment by alcohol** [comment]
Looks promising. Not sure how @Seldaek thinks about it. I personally would have to take some time to read more into the docs of DocSearch to see what options there are etc. If we want to go through with this, we will have to get our own API key of course.

**Comment by julienbourdeau** [comment]
The code already uses [your dedicated API key](https://github.com/composer/getcomposer.org/pull/114/files#diff-4aa5eefc120b066426bfad396a3494fdR53) which is linked to the "getcomposer" index.

With DocSearch, the update of the index is automated, you don't need an Algolia account. We provide the autocomplete as you see it in this PR and you can override CSS to make it match your design better. I'll be happy to answer any question you have.

If you want you can create an account and we'll give you access to the analytics.

**Comment by julienbourdeau** [comment]
Here is the a live demo: http://designer-duck-43670.netlify.com/

Please not that all links will take you to the production website. This is only to test the searchbar.

**Comment by Seldaek** [comment]
@julienbourdeau Thanks, pretty cool! I meant to look into this but glad you did it for me ;) 

I do have an account registered as j.boggiano@seld.be on algolia.com, and I also did a request for a token on the docsearch website (sorry I thought it would be automated.. just thought I could replace the token and get access to it myself) so if you can somehow either approve my request and I update the token or you grant me access to the one you created that'd be great!

**Comment by julienbourdeau** [comment]
For further reference (this was handle privately).

It's better to keep docsearch inside the Algolia account but we provide access to the index and the analytics :)

**Pull request merged**
