### PR TITLE
Remove xdebug warning with 1.3 release

### PR DESCRIPTION
**Pull request by johnstevenson**
The `$install` param looks a bit pointless, but I've added it mainly as a reminder (I have a plan to incorporate this code into the main repo - but that's for next year!)

### CODE REVIEW

**Comment by Seldaek** [comment]
So you are saying you want to keep the xdebug check because it should be used in the future for the diagnose command? Because in this installer code really I don't see  a point to warn about xdebug anymore. In the diagnose command I'd say yes if we see we couldn't disable xdebug then we can warn..

**Comment by johnstevenson** [comment]
> So you are saying you want to keep the xdebug check because it should be used in the future for the diagnose command?

Yes, basically. But I can simply remove it now, if you want, and remember for later.

**Comment by Seldaek** [comment]
No I guess it's fine just wanted to make sure

**Comment by johnstevenson** [comment]
@Seldaek Be handy if something would happen with this, one way or the other. Now that I can use the `installer` script from here in Composer-Setup, it would be good to be able to do so for an upcoming release.

**Comment by Seldaek** [comment]
Yeah sorry it's just I have to update the installer signature every time I merge smth here so I tend to be a bit lazy about installer merges :D

**Pull request merged**
